name: CI
on:
  push:
    branches:
      - main
      - bugfix/**
      - release/**
      - feature/**
      - hotfix/**
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.1'
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Run Composer
        run: composer install